### ISSUE TITLE
Switch to vuer for camera control and visualization

### ISSUE THREAD

**Issue by geyang** [Jarrome/NSLF-OL#1]
Really enjoyed the responsiveness of the demo.

Would you be interested in integrating vuer for the camera control and visualization?

Here are the examples: https://docs.vuer.ai

**Comment by Jarrome** [comment]
Looks cool. 
Really nice to know this, geyang. 

But I currently need to complete new project and donot have time to refactorize the code.
It would be good if you can contribute, or maybe I can find time after my current thing :)
